/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 flower.glb --transform 
Files: flower.glb [1.36MB] > /Users/thomasgertenbach/Documents/isometric-room/public/flower-transformed.glb [323.96KB] (76%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._ndyj_Var10_LOD0.geometry} material={materials.material0} />
    </group>
  )
}

useGLTF.preload('/flower-transformed.glb')
