/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 isometric.glb --transform --instanced 
Files: isometric.glb [1.13MB] > /Users/thomasgertenbach/Documents/isometric-room/public/isometric-transformed.glb [84.32KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/isometric-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bak.geometry} material={nodes.bak.material} />
      <mesh geometry={nodes.water.geometry} material={nodes.water.material} />
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.acacia_leaf} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.bark07} />
    </group>
  )
}

useGLTF.preload('/isometric-transformed.glb')
